# Generated by Django 2.1.1 on 2018-09-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0002_auto_20180913_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
    ]
