# Generated by Django 2.1.1 on 2018-09-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0003_auto_20180929_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='field1',
        ),
        migrations.AddField(
            model_name='user',
            name='field2',
            field=models.CharField(default='number', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='field3',
            field=models.CharField(default='text', max_length=264),
            preserve_default=False,
        ),
    ]
